// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SolarPanelInstallationManagement.Data;

#nullable disable

namespace SolarPanelInstallationManagement.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251220073333_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SolarPanelInstallationManagement.Models.Entities.ConsumerSurvey", b =>
                {
                    b.Property<int>("Sno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Sno"));

                    b.Property<string>("AadharNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Constituency")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ConsumerMobileNo")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ConsumerNameWithSurname")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DtrStructureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("ExistingContractedLoadKW")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("ExistingDtrCapacityKva")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("FeederName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool?>("HasOtherDomesticServices")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsBeneficiaryUnderGJScheme")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNameChangeRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("LatitudeLongitude")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Mandal")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PoleNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SSName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ServiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("ShadeFreeRoofAreaSqFt")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TypeOfRoof")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("USCNO")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Village")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Sno");

                    b.ToTable("consumer_survey", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
